language: rust
rust:
  - nightly
  - stable
cache: cargo

branches:
  only:
    - staging
    - trying
    - master

os: linux
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgtk-3-dev;
    fi

script:
- cargo test --all
