[package]
name = "gitters"
version = "0.1.0"
authors = ["Ilya Bogdanov <fumlead@gmail.com>"]

[dependencies]
gitter = "0.2.0"
gtk = { version = "0.3.0", features = ["v3_16"] }
relm = "0.11.0"
futures-glib = "0.3.2"
relm-derive = "0.11.0"
